wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    code_path: code/htpm.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.6
    start_time: 1696912827.157594
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.6
      5: 0.13.2
      8:
      - 2
      - 5
batch:
  desc: null
  value: 1
blra:
  desc: null
  value: true
data_dir:
  desc: null
  value: /jet/home/lisun/work/xinliu/images/fewshot
dataset:
  desc: null
  value: isic
device_ids:
  desc: null
  value:
  - 0
extra_dir:
  desc: null
  value: test222
feature:
  desc: null
  value: resnet12
gamma:
  desc: null
  value: 0.05
gpu:
  desc: null
  value: '0'
lamb:
  desc: null
  value: 0.25
lr:
  desc: null
  value: 0.1
max_epoch:
  desc: null
  value: 80
milestones:
  desc: null
  value:
  - 60
  - 70
mix:
  desc: null
  value: true
no_wandb:
  desc: null
  value: false
num_gpu:
  desc: null
  value: 1
query:
  desc: null
  value: 15
resume:
  desc: null
  value: ''
save_all:
  desc: null
  value: false
save_path:
  desc: null
  value: checkpoints/isic/5shot-2way/test222
seed:
  desc: null
  value: 1
self_method:
  desc: null
  value: scr
shot:
  desc: null
  value: 5
temperature:
  desc: null
  value: 0.2
temperature_attn:
  desc: null
  value: 5.0
test_episode:
  desc: null
  value: 2000
val_episode:
  desc: null
  value: 200
way:
  desc: null
  value: 2
